### ISSUE TITLE
Strange error

### ISSUE THREAD

**Issue by FunnyUser** [vialink/viacrypt#6]
I have several computers that keep getting error (Windows 7 64bit, FireFox39-43 and IE11):
TypeError: Property 'undefined' of object #<Object> is not a function
    at Object.handle (/var/www/viacrypt/src/i18n.js:100:41)
    at next (/var/www/viacrypt/node_modules/connect/lib/proto.js:190:15)
    at Object.handle (/var/www/viacrypt/node_modules/connect/lib/middleware/responseTime.js:30:5)
    at next (/var/www/viacrypt/node_modules/connect/lib/proto.js:190:15)
    at Object.logger (/var/www/viacrypt/node_modules/connect/lib/middleware/logger.js:156:5)
    at next (/var/www/viacrypt/node_modules/connect/lib/proto.js:190:15)
    at Function.app.handle (/var/www/viacrypt/node_modules/connect/lib/proto.js:198:3)
    at Server.app (/var/www/viacrypt/node_modules/connect/lib/connect.js:65:37)
    at Server.EventEmitter.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2108:12)

From most computers everything working just fine.

**Comment by jansegre** [comment]
That is certainly an error on the server code, most likely on the multi-language (i18n) side.

Can you tell me what language is your browser in? (Technically I'd like to know the `Accept-Language` request header if you can figure that out)

**Comment by FunnyUser** [comment]
Browser language is English, Accept-Language Russian.
